Empresa02/Controllers/ContasPagarController.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SistemaCadastro.Models;

namespace SistemaCadastro.Controllers
{
    public class ContasPagarController : Controller
    {
        //Metodo para simular a busca de dados de alunos no BD
        private List<ContasPagar> ObterContasPagar()
        {
            var listaDeContasPagar = new List<ContasPagar>
            {
                new ContasPagar { ContaID = 1, ValorConta = 1000, ValorPago = 500 },
                new ContasPagar { ContaID = 2, ValorConta = 2500, ValorPago = 2500 },
                new ContasPagar { ContaID = 3, ValorConta = 500, ValorPago = 500 }
            };
            return listaDeContasPagar.OrderBy(a => a.ContaID).ToList();
        }
        public IActionResult ContasPagar()
        {
            var contaspagar = ObterContasPagar();
            return View(contaspagar);
        }
    }
}

Empresa02/Controllers/ContasReceberController.cs
using SistemaCadastro.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;

namespace SistemaCadastro.Controllers
{
    public class ContasReceberController : Controller
    {
        //Metodo para simular a busca de dados de alunos no BD
        private List<ContasReceber> ObterContasReceber()
        {
            var listaDeContasReceber = new List<ContasReceber>
            {
                new ContasReceber { ContaID = 1, ValorConta = 1000, ValorRecebido = 500 },
                new ContasReceber { ContaID = 2, ValorConta = 2500, ValorRecebido = 2500 },
                new ContasReceber { ContaID = 3, ValorConta = 500, ValorRecebido = 500 }
            };
            return listaDeContasReceber.OrderBy(a => a.ContaID).ToList();
        }
        public IActionResult ContasReceber()
        {
            var contasreceber = ObterContasReceber();
            return View(contasreceber);
        }
    }
}

Empresa02/Controllers/Global/PrincipalController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaCadastro.Controllers.Global
{
    public class PrincipalController : Controller
    {
        public IActionResult Principal()
        {
            return View("~/Views/Global/Principal.cshtml");
        }
    }
}

Empresa02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Badrock System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaCadastro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Global" asp-controller="Principal" asp-action="Principal">Badrock System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Global" asp-controller="Usuario" asp-action="Usuario">Todos os Usuários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Cadastro" asp-controller="Fornecedores" asp-action="Fornecedores">Listagem de Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Financeiro" asp-controller="ContasPagar" asp-action="ContasPagar">Contas a Pagar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Financeiro" asp-controller="ContasReceber" asp-action="ContasReceber">Contas a Receber</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Badrock System</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>